### ISSUE TITLE
Error while refreshing pending block on main

### ISSUE THREAD

**Issue by Konstantin35** [sero-cash/mine-pool#4]
Periodically includes such logs what is the problem
```
2019/08/16 11:46:58 Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2019/08/16 11:46:58 Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
`cmd="bin/gero --config ${CONFIG_PATH} --datadir ${DEFAULT_DATD_DIR} --maxpeers=25 --rpc --unlock ${WALLET} --password ${PASS} --port ${DEFAULT_PORT}"`

in node surmounting
 ```
Verify Tx Error reason="txs.verify in_o already in nils"        hash=0xb503b3bddad680a9d02e1a5925603655c3c6847df80cc0845d5ac686d1832e9f
ERROR[08-16|12:39:59.699] validateTx error                         hash=0xb503b3bddad680a9d02e1a5925603655c3c6847df80cc0845d5ac686d1832e9f verify stx err="Verify Tx Error: resean=txs.verify in_o already in nils , hash=0xb503b3bddad680a9d02e1a5925603655c3c6847df80cc0845d5ac686d1832e9f"
```

**Comment by edcomrocha** [comment]
> Periodically includes such logs what is the problem
> 
> ```
> 2019/08/16 11:46:58 Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> 2019/08/16 11:46:58 Error while refreshing pending block on main: Post http://127.0.0.1:8545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> ```
> 
> `cmd="bin/gero --config ${CONFIG_PATH} --datadir ${DEFAULT_DATD_DIR} --maxpeers=25 --rpc --unlock ${WALLET} --password ${PASS} --port ${DEFAULT_PORT}"`
> 
> in node surmounting
> 
> ```
> Verify Tx Error reason="txs.verify in_o already in nils"        hash=0xb503b3bddad680a9d02e1a5925603655c3c6847df80cc0845d5ac686d1832e9f
> ERROR[08-16|12:39:59.699] validateTx error                         hash=0xb503b3bddad680a9d02e1a5925603655c3c6847df80cc0845d5ac686d1832e9f verify stx err="Verify Tx Error: resean=txs.verify in_o already in nils , hash=0xb503b3bddad680a9d02e1a5925603655c3c6847df80cc0845d5ac686d1832e9f"
> ```

Hello, sorry for reopening after a long time.

I'm having the same problem here, were you able to fix it at the time?

Thanks
